### ISSUE TITLE
Save Demo Issue on Signup

### ISSUE THREAD

**Issue by solveguide** [solveguide/solveguide#60]
## Tasks
- [x] Navigate automatically after registration to dashboard
- [x] save the demo issue when first viewing the dashboard

## Description
Given that a demo solve has been created.
When an account is created
Then the demo issue is saved to the new account.
And it will show up on the user's dashboard.

## User Story
As a new user I want to create an account so I can save the work I just did.

## Design & Copy Requirements
- [ ] Is there a design requirement for this feature? (yes/no)
- [ ] Is there a copywriting requirement for this feature? (yes/no)

### Design Details
If design is required, add initial design notes here or attach files.

### Copy Details
If copywriting is needed, specify the text or content changes here.

## BDD Specs
- [ ] Are BDD specifications defined for this feature? (yes/no)

### BDD Scenario
```gherkin
Scenario: [Title]
  Given [context]
  And [some more context]...
  When [event]
  Then [outcome]
  And [another outcome]...

**Comment by solveguide** [comment]
Create the Issue Model:
Define the Issue model with proper JSON serialization and deserialization functions.

Handle User Registration:
Utilize firebase_ui_auth to handle user registration and track user creation events.

Anonymous Login (Optional):
Consider using anonymous login to allow users to interact with the app before registering.

Save Demo Issue:
Save a demo issue to Firebase Firestore when the user registers.
