### ISSUE TITLE
Bloc for issues

### ISSUE THREAD

**Issue by solveguide** [solveguide/solveguide#71]
### Milestones
- [x] rip out the entire demo (pages, blue_container, changenotifier, etc)
- [x] get login working on homepage/dashboard with auth bloc
- [x] move all firebase methods to repository class
- [x] create issue Bloc
- [x] Create Issue solving page using bloc

### BDD Scenario
```gherkin
Scenario: Issues Bloc
  Given that issues are regulated using Bloc
  When a user creates an event
  Then the issue state is regulated using Bloc
  ```

## Description
Create an issue solving process that uses Bloc instead of the demo monster and blue_container

## User Story
As a [type of user], I want [some goal] so that [some reason].

## Design & Copy Requirements
- [ ] Is there a design requirement for this feature? (yes/no)
- [ ] Is there a copywriting requirement for this feature? (yes/no)

### Design Details
If design is required, add initial design notes here or attach files.

### Copy Details
If copywriting is needed, specify the text or content changes here.

**Comment by solveguide** [comment]
Decided to create another issue for the issue solving process.
